# Site settings
title: State of the Map 2020
email: sotm@openstreetmap.org
description: "Join us for three days of talks, discussions and workshops around the free and open map of the world."
url: "http://2020.stateofthemap.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: 'rgb(255, 184, 28)'
  primary-light: 'rgb(0, 119, 73)'
  links: '#000'
  links-light: '#333'
  links-white: '#333'
  text: '#030303'
  background-light: '#fff'
  text-light: '#fff'

# Settings for map tiles used in leaflet maps
map_tiles:
  url: 'https://api.openrouteservice.org/mapsurfer/{z}/{x}/{y}.png?api_key={accessToken}'
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'
  maxZoom: 18,
  accessToken: '5b3ce3597851110001cf624824a7744e191a4de2820df026fed1efa7'

# Repo files to not include in built site
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: /:title/
relative_permalinks: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:title/
